const initialProducts = [
  // শস্য (1-6)
  {
    id: 1,
    name: "চাল (মিনিকেট)",
    nameEn: "Miniket Rice",
    category: "শস্য",
    unit: "কেজি",
    price: "75",
    prevPrice: "72",
    icon: "🌾",
  },
  {
    id: 2,
    name: "চাল (নাজিরশাইল)",
    nameEn: "Nazirshail Rice",
    category: "শস্য",
    unit: "কেজি",
    price: "85",
    prevPrice: "82",
    icon: "🌾",
  },
  {
    id: 3,
    name: "চাল (পোলাও)",
    nameEn: "Polao Rice",
    category: "শস্য",
    unit: "কেজি",
    price: "125",
    prevPrice: "120",
    icon: "🌾",
  },
  {
    id: 4,
    name: "আটা",
    nameEn: "Wheat Flour",
    category: "শস্য",
    unit: "কেজি",
    price: "50",
    prevPrice: "55",
    icon: "🌾",
  },
  {
    id: 5,
    name: "গম",
    nameEn: "Wheat",
    category: "শস্য",
    unit: "কেজি",
    price: "45",
    prevPrice: "48",
    icon: "🌾",
  },
  {
    id: 6,
    name: "ভুট্টা",
    nameEn: "Corn",
    category: "শস্য",
    unit: "কেজি",
    price: "35",
    prevPrice: "40",
    icon: "🌽",
  },

  // ডাল (7-11)
  {
    id: 7,
    name: "ডাল (মসুর)",
    nameEn: "Lentils",
    category: "ডাল",
    unit: "কেজি",
    price: "140",
    prevPrice: "135",
    icon: "🫘",
  },
  {
    id: 8,
    name: "মুগ ডাল",
    nameEn: "Mung Lentils",
    category: "ডাল",
    unit: "কেজি",
    price: "170",
    prevPrice: "160",
    icon: "🫘",
  },
  {
    id: 9,
    name: "ছোলা",
    nameEn: "Chickpeas",
    category: "ডাল",
    unit: "কেজি",
    price: "115",
    prevPrice: "110",
    icon: "🫘",
  },
  {
    id: 10,
    name: "বুটের ডাল",
    nameEn: "Split Chickpeas",
    category: "ডাল",
    unit: "কেজি",
    price: "125",
    prevPrice: "120",
    icon: "🫘",
  },
  {
    id: 11,
    name: "খেসারি ডাল",
    nameEn: "Khesari Lentils",
    category: "ডাল",
    unit: "কেজি",
    price: "105",
    prevPrice: "100",
    icon: "🫘",
  },

  // তেল (12-18)
  {
    id: 12,
    name: "সয়াবিন তেল",
    nameEn: "Soybean Oil",
    category: "তেল",
    unit: "লিটার",
    price: "172",
    prevPrice: "168",
    icon: "🫙",
  },
  {
    id: 13,
    name: "সরিষার তেল",
    nameEn: "Mustard Oil",
    category: "তেল",
    unit: "লিটার",
    price: "240",
    prevPrice: "220",
    icon: "🫙",
  },
  {
    id: 14,
    name: "পাম তেল",
    nameEn: "Palm Oil",
    category: "তেল",
    unit: "লিটার",
    price: "155",
    prevPrice: "150",
    icon: "🫙",
  },
  {
    id: 15,
    name: "রাইস ব্র্যান অয়েল",
    nameEn: "Rice Bran Oil",
    category: "তেল",
    unit: "লিটার",
    price: "195",
    prevPrice: "185",
    icon: "🍾",
  },
  {
    id: 16,
    name: "সূর্যমুখী তেল",
    nameEn: "Sunflower Oil",
    category: "তেল",
    unit: "লিটার",
    price: "280",
    prevPrice: "260",
    icon: "🌻",
  },
  {
    id: 17,
    name: "অলিভ অয়েল",
    nameEn: "Olive Oil",
    category: "তেল",
    unit: "লিটার",
    price: "1200",
    prevPrice: "1100",
    icon: "🫒",
  },
  {
    id: 18,
    name: "নারকেল তেল",
    nameEn: "Coconut Oil",
    category: "তেল",
    unit: "লিটার",
    price: "520",
    prevPrice: "480",
    icon: "🥥",
  },

  // সবজি (19-31)
  {
    id: 19,
    name: "পেঁয়াজ (দেশি)",
    nameEn: "Onion",
    category: "সবজি",
    unit: "কেজি",
    price: "110",
    prevPrice: "90",
    icon: "🧅",
  },
  {
    id: 20,
    name: "রসুন",
    nameEn: "Garlic",
    category: "সবজি",
    unit: "কেজি",
    price: "250",
    prevPrice: "220",
    icon: "🧄",
  },
  {
    id: 21,
    name: "আলু",
    nameEn: "Potato",
    category: "সবজি",
    unit: "কেজি",
    price: "50",
    prevPrice: "45",
    icon: "🥔",
  },
  {
    id: 22,
    name: "টমেটো",
    nameEn: "Tomato",
    category: "সবজি",
    unit: "কেজি",
    price: "80",
    prevPrice: "60",
    icon: "🍅",
  },
  {
    id: 23,
    name: "বেগুন",
    nameEn: "Eggplant",
    category: "সবজি",
    unit: "কেজি",
    price: "90",
    prevPrice: "70",
    icon: "🍆",
  },
  {
    id: 24,
    name: "কাঁচা মরিচ",
    nameEn: "Green Chili",
    category: "সবজি",
    unit: "কেজি",
    price: "160",
    prevPrice: "120",
    icon: "🌶️",
  },
  {
    id: 25,
    name: "লাউ",
    nameEn: "Bottle Gourd",
    category: "সবজি",
    unit: "পিস",
    price: "80",
    prevPrice: "60",
    icon: "🥒",
  },
  {
    id: 26,
    name: "করলা",
    nameEn: "Bitter Gourd",
    category: "সবজি",
    unit: "কেজি",
    price: "100",
    prevPrice: "80",
    icon: "🥒",
  },
  {
    id: 27,
    name: "পটল",
    nameEn: "Pointed Gourd",
    category: "সবজি",
    unit: "কেজি",
    price: "80",
    prevPrice: "65",
    icon: "🥒",
  },
  {
    id: 28,
    name: "বাঁধাকপি",
    nameEn: "Cabbage",
    category: "সবজি",
    unit: "পিস",
    price: "40",
    prevPrice: "50",
    icon: "🥬",
  },
  {
    id: 29,
    name: "ফুলকপি",
    nameEn: "Cauliflower",
    category: "সবজি",
    unit: "পিস",
    price: "50",
    prevPrice: "60",
    icon: "🥦",
  },
  {
    id: 30,
    name: "গাজর",
    nameEn: "Carrot",
    category: "সবজি",
    unit: "কেজি",
    price: "70",
    prevPrice: "55",
    icon: "🥕",
  },
  {
    id: 31,
    name: "শসা",
    nameEn: "Cucumber",
    category: "সবজি",
    unit: "কেজি",
    price: "60",
    prevPrice: "50",
    icon: "🥒",
  },

  // মাংস (32-35)
  {
    id: 32,
    name: "মুরগি (ব্রয়লার)",
    nameEn: "Broiler Chicken",
    category: "মাংস",
    unit: "কেজি",
    price: "210",
    prevPrice: "195",
    icon: "🍗",
  },
  {
    id: 33,
    name: "দেশি মুরগি",
    nameEn: "Desi Chicken",
    category: "মাংস",
    unit: "কেজি",
    price: "580",
    prevPrice: "550",
    icon: "🍗",
  },
  {
    id: 34,
    name: "গরুর মাংস",
    nameEn: "Beef",
    category: "মাংস",
    unit: "কেজি",
    price: "780",
    prevPrice: "750",
    icon: "🥩",
  },
  {
    id: 35,
    name: "খাসির মাংস",
    nameEn: "Mutton",
    category: "মাংস",
    unit: "কেজি",
    price: "1150",
    prevPrice: "1100",
    icon: "🥩",
  },

  // মাছ (36-41)
  {
    id: 36,
    name: "রুই মাছ",
    nameEn: "Rohu Fish",
    category: "মাছ",
    unit: "কেজি",
    price: "350",
    prevPrice: "320",
    icon: "🐟",
  },
  {
    id: 37,
    name: "কাতলা মাছ",
    nameEn: "Katla Fish",
    category: "মাছ",
    unit: "কেজি",
    price: "380",
    prevPrice: "350",
    icon: "🐟",
  },
  {
    id: 38,
    name: "পাঙ্গাস মাছ",
    nameEn: "Pangas Fish",
    category: "মাছ",
    unit: "কেজি",
    price: "200",
    prevPrice: "180",
    icon: "🐟",
  },
  {
    id: 39,
    name: "তেলাপিয়া",
    nameEn: "Tilapia Fish",
    category: "মাছ",
    unit: "কেজি",
    price: "240",
    prevPrice: "220",
    icon: "🐟",
  },
  {
    id: 40,
    name: "চিংড়ি",
    nameEn: "Shrimp",
    category: "মাছ",
    unit: "কেজি",
    price: "850",
    prevPrice: "750",
    icon: "🦐",
  },
  {
    id: 41,
    name: "ইলিশ মাছ",
    nameEn: "Hilsa Fish",
    category: "মাছ",
    unit: "কেজি",
    price: "1650",
    prevPrice: "1550",
    icon: "🐠",
  },

  // দুগ্ধ (42-45, 61-65)
  {
    id: 42,
    name: "ডিম (ফার্ম)",
    nameEn: "Egg",
    category: "দুগ্ধ",
    unit: "হালি",
    price: "52",
    prevPrice: "48",
    icon: "🥚",
  },
  {
    id: 43,
    name: "দুধ (তরল)",
    nameEn: "Fresh Milk",
    category: "দুগ্ধ",
    unit: "লিটার",
    price: "90",
    prevPrice: "85",
    icon: "🥛",
  },
  {
    id: 44,
    name: "দই",
    nameEn: "Yogurt",
    category: "দুগ্ধ",
    unit: "কেজি",
    price: "150",
    prevPrice: "130",
    icon: "🥛",
  },
  {
    id: 45,
    name: "ঘি (দেশি)",
    nameEn: "Ghee",
    category: "দুগ্ধ",
    unit: "কেজি",
    price: "1350",
    prevPrice: "1250",
    icon: "🧈",
  },

  // মশলা (46-51, 76-77)
  {
    id: 46,
    name: "চিনি",
    nameEn: "Sugar",
    category: "মশলা",
    unit: "কেজি",
    price: "135",
    prevPrice: "140",
    icon: "🍬",
  },
  {
    id: 47,
    name: "লবণ",
    nameEn: "Salt",
    category: "মশলা",
    unit: "কেজি",
    price: "42",
    prevPrice: "38",
    icon: "🧂",
  },
  {
    id: 48,
    name: "হলুদ গুঁড়া",
    nameEn: "Turmeric",
    category: "মশলা",
    unit: "কেজি",
    price: "380",
    prevPrice: "350",
    icon: "🧂",
  },
  {
    id: 49,
    name: "মরিচ গুঁড়া",
    nameEn: "Chili Powder",
    category: "মশলা",
    unit: "কেজি",
    price: "450",
    prevPrice: "420",
    icon: "🌶️",
  },
  {
    id: 50,
    name: "জিরা",
    nameEn: "Cumin",
    category: "মশলা",
    unit: "কেজি",
    price: "850",
    prevPrice: "800",
    icon: "🧂",
  },
  {
    id: 51,
    name: "ধনে",
    nameEn: "Coriander",
    category: "মশলা",
    unit: "কেজি",
    price: "220",
    prevPrice: "200",
    icon: "🧂",
  },

  // ফল (52-60)
  {
    id: 52,
    name: "আপেল (গালা)",
    nameEn: "Apple (Gala)",
    category: "ফল",
    unit: "কেজি",
    price: "320",
    prevPrice: "300",
    icon: "🍎",
  },
  {
    id: 53,
    name: "মাল্টা",
    nameEn: "Malta",
    category: "ফল",
    unit: "কেজি",
    price: "280",
    prevPrice: "260",
    icon: "🍊",
  },
  {
    id: 54,
    name: "কলা (সাগর)",
    nameEn: "Banana (Sagor)",
    category: "ফল",
    unit: "ডজন",
    price: "120",
    prevPrice: "110",
    icon: "🍌",
  },
  {
    id: 55,
    name: "আঙ্গুর (কালো)",
    nameEn: "Grapes (Black)",
    category: "ফল",
    unit: "কেজি",
    price: "450",
    prevPrice: "420",
    icon: "🍇",
  },
  {
    id: 56,
    name: "তরমুজ",
    nameEn: "Watermelon",
    category: "ফল",
    unit: "পিস",
    price: "350",
    prevPrice: "400",
    icon: "🍉",
  },
  {
    id: 57,
    name: "পেঁপে (পাকা)",
    nameEn: "Papaya",
    category: "ফল",
    unit: "কেজি",
    price: "90",
    prevPrice: "80",
    icon: "🥭",
  },
  {
    id: 58,
    name: "আনারস",
    nameEn: "Pineapple",
    category: "ফল",
    unit: "পিস",
    price: "50",
    prevPrice: "45",
    icon: "🍍",
  },
  {
    id: 59,
    name: "পেয়ারা",
    nameEn: "Guava",
    category: "ফল",
    unit: "কেজি",
    price: "80",
    prevPrice: "70",
    icon: "🍏",
  },
  {
    id: 60,
    name: "ডালিম/আনার",
    nameEn: "Pomegranate",
    category: "ফল",
    unit: "কেজি",
    price: "480",
    prevPrice: "450",
    icon: "🍎",
  },

  // দুগ্ধ (Extra)
  {
    id: 61,
    name: "ডানো গুঁড়া দুধ",
    nameEn: "Dano Milk",
    category: "দুগ্ধ",
    unit: "৫০০ গ্রাম",
    price: "450",
    prevPrice: "440",
    icon: "🥛",
  },
  {
    id: 62,
    name: "ডিপ্লোমা দুধ",
    nameEn: "Diploma Milk",
    category: "দুগ্ধ",
    unit: "৫০০ গ্রাম",
    price: "460",
    prevPrice: "450",
    icon: "🥛",
  },
  {
    id: 63,
    name: "পনির",
    nameEn: "Cheese",
    category: "দুগ্ধ",
    unit: "কেজি",
    price: "850",
    prevPrice: "800",
    icon: "🧀",
  },
  {
    id: 64,
    name: "মাখন",
    nameEn: "Butter",
    category: "দুগ্ধ",
    unit: "২০০ গ্রাম",
    price: "270",
    prevPrice: "250",
    icon: "🧈",
  },
  {
    id: 65,
    name: "মিষ্টি দই",
    nameEn: "Sweet Yogurt",
    category: "দুগ্ধ",
    unit: "কেজি",
    price: "260",
    prevPrice: "250",
    icon: "🥣",
  },

  // টয়লেট্রিজ (66-75)
  {
    id: 66,
    name: "লাক্স সাবান",
    nameEn: "Lux Soap",
    category: "টয়লেট্রিজ",
    unit: "পিস",
    price: "75",
    prevPrice: "70",
    icon: "🧼",
  },
  {
    id: 67,
    name: "লাইফবয় সাবান",
    nameEn: "Lifebuoy Soap",
    category: "টয়লেট্রিজ",
    unit: "পিস",
    price: "60",
    prevPrice: "58",
    icon: "🧼",
  },
  {
    id: 68,
    name: "হুইল পাউডার",
    nameEn: "Wheel Powder",
    category: "টয়লেট্রিজ",
    unit: "১ কেজি",
    price: "120",
    prevPrice: "115",
    icon: "🧺",
  },
  {
    id: 69,
    name: "সার্ফ এক্সেল",
    nameEn: "Surf Excel",
    category: "টয়লেট্রিজ",
    unit: "১ কেজি",
    price: "240",
    prevPrice: "230",
    icon: "🧺",
  },
  {
    id: 70,
    name: "টুথপেস্ট",
    nameEn: "Toothpaste",
    category: "টয়লেট্রিজ",
    unit: "১৪০ গ্রাম",
    price: "140",
    prevPrice: "135",
    icon: "🪥",
  },
  {
    id: 71,
    name: "শ্যাম্পু",
    nameEn: "Shampoo",
    category: "টয়লেট্রিজ",
    unit: "১৮০ মিলি",
    price: "350",
    prevPrice: "330",
    icon: "🧴",
  },
  {
    id: 72,
    name: "হারপিক",
    nameEn: "Harpic",
    category: "টয়লেট্রিজ",
    unit: "৭৫০ মিলি",
    price: "185",
    prevPrice: "180",
    icon: "🚽",
  },
  {
    id: 73,
    name: "হ্যান্ডওয়াশ",
    nameEn: "Handwash",
    category: "টয়লেট্রিজ",
    unit: "প্যাক",
    price: "90",
    prevPrice: "85",
    icon: "🧼",
  },
  {
    id: 74,
    name: "টিস্যু",
    nameEn: "Tissue Paper",
    category: "টয়লেট্রিজ",
    unit: "প্যাক",
    price: "50",
    prevPrice: "48",
    icon: "🧻",
  },
  {
    id: 75,
    name: "ডিশওয়াশ",
    nameEn: "Vim Liquid",
    category: "টয়লেট্রিজ",
    unit: "৫০০ মিলি",
    price: "110",
    prevPrice: "100",
    icon: "🧽",
  },

  // নাস্তা ও মশলা (Extra)
  {
    id: 76,
    name: "চা পাতা",
    nameEn: "Tea Leaves",
    category: "মশলা",
    unit: "৫০০ গ্রাম",
    price: "250",
    prevPrice: "240",
    icon: "☕",
  },
  {
    id: 77,
    name: "কফি",
    nameEn: "Coffee",
    category: "মশলা",
    unit: "৫০ গ্রাম",
    price: "320",
    prevPrice: "310",
    icon: "☕",
  },
  {
    id: 78,
    name: "বিস্কুট",
    nameEn: "Lexus Biscuit",
    category: "নাস্তা",
    unit: "প্যাক",
    price: "50",
    prevPrice: "45",
    icon: "🍪",
  },
  {
    id: 79,
    name: "নুডলস",
    nameEn: "Maggi Noodles",
    category: "নাস্তা",
    unit: "৮ প্যাক",
    price: "160",
    prevPrice: "150",
    icon: "🍜",
  },
  {
    id: 80,
    name: "মধু (সুন্দরবন)",
    nameEn: "Honey",
    category: "অন্যান্য",
    unit: "১ কেজি",
    price: "850",
    prevPrice: "800",
    icon: "🍯",
  },
];

export default initialProducts;
