import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// সঠিক পাথ দিন:
import Header from "./components/layouts/Header";
import Footer from "./components/layouts/Footer";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header /> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
